name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  d_info: ^0.2.2
  flutter:
    sdk: flutter
  gap: ^3.0.1
  http: ^1.2.2
  intl: ^0.18.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/Himmel_guru.jpeg